HOST: http://www.google.com/

--- Domotic API v1 ---
---
Domotic app API
---
--
Infixit Box resources
The following is a section of resources related to the shopping cart
--

--
Returns heat map matrix from infrared sensor
--

GET /heatmap.py
< 200
< Content-Type: application/json
{"heatmaprow": {"v1": 26.75, "v10": 31.25, "v11": 26.25, "v12": 23.25, "v13": 23.25, "v14": 22.5, "v15": 22.0, "v16": 22.75, "v17": 36.75, "v18": 36.25, "v19": 33.25, "v2": 25.5, "v20": 25.75, "v21": 23.0, "v22": 22.5, "v23": 22.0, "v24": 22.0, "v25": 43.25, "v26": 41.0, "v27": 36.0, "v28": 29.75, "v29": 22.75, "v3": 24.25, "v30": 22.5, "v31": 22.5, "v32": 22.75, "v33": 46.0, "v34": 45.25, "v35": 36.25, "v36": 30.75, "v37": 22.75, "v38": 23.0, "v39": 23.0, "v4": 23.25, "v40": 22.75, "v41": 39.75, "v42": 39.0, "v43": 36.5, "v44": 27.75, "v45": 23.75, "v46": 22.75, "v47": 22.75, "v48": 23.5, "v49": 35.0, "v5": 23.25, "v50": 35.25, "v51": 31.0, "v52": 24.75, "v53": 24.25, "v54": 23.0, "v55": 23.75, "v56": 22.75, "v57": 29.25, "v58": 27.0, "v59": 26.5, "v6": 23.5, "v60": 23.75, "v61": 23.75, "v62": 23.0, "v63": 23.5, "v64": 23.5, "v7": 23.25, "v8": 23.5, "v9": 32.25}, "sensortemp": 25.875}

--
Get lights current status
--

GET /read-lights.py
< 200
< Content-Type: application/json
{ "s1": "on",  "s2" : "off" }

--
Switch on light1
--

GET /switchonl1.py
< 200
< Content-Type: application/json
{ "s1": "on" }

--
Switch on light2
--

GET /switchonl2.py
< 200
< Content-Type: application/json
{ "s2": "on" }

--
Switch off light1
--

GET /switchoffl1.py
< 200
< Content-Type: application/json
{ "s1": "off" }

--
Switch off light2
--

GET /switchoffl2.py
< 200
< Content-Type: application/json
{ "s2": "off" }


